

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PitchesAndNotes.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class PitchesAndNotesEntities3 : DbContext
{
    public PitchesAndNotesEntities3()
        : base("name=PitchesAndNotesEntities3")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Member> Members { get; set; }

}

}

